### ISSUE TITLE
Lorentzian angle calculation is different from Bob Denny source material

### ISSUE THREAD

**Issue by chris125577** [daleghent/nina-moon-angle#2]
I think the Lorentzian modified angle calculation is incorrect. If a full moon occurs on day 15, a 15% illuminated moon, occurs about day 19. That was the case on 28th October in the UK

The Bob Denny formula, assuming a 120//14 setting, would be 120/(1+(0.5 - 19/14)^2)  = 70 deg
Using same 120 degrees //14 days in the plugin , it calculated 99.15 degrees on 28 Oct. (screen shot shared on Discord on 28th)

The Berkely obsy is obviously more scientific based - so their calculation is quite conservative but it seems that the plugin is even more so.  This is a really useful plugin and I hope this helps to make it even more useful. 
Right now - the moon is almost fully illuminated but the moon angle plugin is saying 96 deg from 120 - which makes me wonder if it is the day number that is wrongly referenced?  Hope that helps
regards Chris

**Comment by daleghent** [comment]
Addressed!
